#!/usr/bin/env bash
#
# exsocks 高并发内核参数调优脚本
#
# 用途：在 Linux 服务器上一键调优内核参数，支撑 10000+ 并发 SOCKS5 代理
# 用法：sudo bash scripts/tune-kernel.sh [--persist]
#   --persist  将参数写入 /etc/sysctl.d/99-exsocks.conf 使其重启后生效
#
# 调优前会自动打印当前值，方便对比和回滚

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

PERSIST=false
SYSCTL_CONF="/etc/sysctl.d/99-exsocks.conf"

if [[ "${1:-}" == "--persist" ]]; then
    PERSIST=true
fi

if [[ "$(uname)" != "Linux" ]]; then
    echo -e "${RED}[ERROR] This script is designed for Linux only.${NC}"
    echo "macOS does not use the same sysctl parameters."
    exit 1
fi

if [[ $EUID -ne 0 ]]; then
    echo -e "${RED}[ERROR] This script must be run as root (use sudo).${NC}"
    exit 1
fi

# ============================================================
# 调优参数定义
# ============================================================
declare -A PARAMS=(
    # TCP 连接队列：accept 队列上限，防止高并发时 SYN 被丢弃
    ["net.core.somaxconn"]=65535

    # SYN 半连接队列：防止 SYN flood 或突发连接导致队列溢出
    ["net.ipv4.tcp_max_syn_backlog"]=65535

    # 临时端口范围：代理向目标发起连接时消耗的本地端口
    # 扩大到 1024-65535，提供约 64000 个可用端口
    ["net.ipv4.ip_local_port_range"]="1024 65535"

    # 允许 TIME_WAIT 状态的端口被新连接复用
    # 高频短连接场景下避免端口耗尽
    ["net.ipv4.tcp_tw_reuse"]=1

    # 系统级最大文件描述符数
    ["fs.file-max"]=1048576

    # 网络设备接收队列长度，防止突发流量丢包
    ["net.core.netdev_max_backlog"]=65535

    # TCP 读/写缓冲区自动调优范围 (min, default, max) 单位：字节
    # min=4KB, default=128KB, max=16MB
    ["net.ipv4.tcp_rmem"]="4096 131072 16777216"
    ["net.ipv4.tcp_wmem"]="4096 131072 16777216"

    # 全局 TCP 内存限制 (pages)：min, pressure, max
    # 约 384MB, 512MB, 768MB (假设 4KB page)
    ["net.ipv4.tcp_mem"]="98304 131072 196608"

    # 开启 TCP 快速回收和窗口缩放
    ["net.ipv4.tcp_window_scaling"]=1

    # 减少 FIN_WAIT2 超时时间（默认 60s → 15s）
    ["net.ipv4.tcp_fin_timeout"]=15

    # 减少 keepalive 探测间隔，更快发现死连接
    ["net.ipv4.tcp_keepalive_time"]=300
    ["net.ipv4.tcp_keepalive_intvl"]=15
    ["net.ipv4.tcp_keepalive_probes"]=5
)

# ============================================================
# 打印当前值
# ============================================================
echo -e "${CYAN}============================================================${NC}"
echo -e "${CYAN}  exsocks Kernel Parameter Tuning${NC}"
echo -e "${CYAN}============================================================${NC}"
echo ""
echo -e "${YELLOW}[INFO] Current values before tuning:${NC}"
echo ""

printf "%-42s %s\n" "PARAMETER" "CURRENT VALUE"
printf "%-42s %s\n" "-----------------------------------------" "--------------------"
for key in $(echo "${!PARAMS[@]}" | tr ' ' '\n' | sort); do
    current=$(sysctl -n "$key" 2>/dev/null | tr '\t' ' ' || echo "N/A")
    printf "%-42s %s\n" "$key" "$current"
done

echo ""

# ============================================================
# 应用调优参数
# ============================================================
echo -e "${GREEN}[INFO] Applying tuned values...${NC}"
echo ""

FAILED=0
for key in $(echo "${!PARAMS[@]}" | tr ' ' '\n' | sort); do
    value="${PARAMS[$key]}"
    if sysctl -w "$key=$value" > /dev/null 2>&1; then
        echo -e "  ${GREEN}✓${NC} $key = $value"
    else
        echo -e "  ${RED}✗${NC} $key = $value (failed)"
        FAILED=$((FAILED + 1))
    fi
done

echo ""

# ============================================================
# 调整进程级文件描述符限制
# ============================================================
echo -e "${GREEN}[INFO] Checking ulimit -n (open files)...${NC}"
CURRENT_ULIMIT=$(ulimit -n 2>/dev/null || echo "unknown")
echo "  Current ulimit -n: $CURRENT_ULIMIT"

if [[ "$CURRENT_ULIMIT" != "unknown" ]] && [[ "$CURRENT_ULIMIT" -lt 65535 ]]; then
    echo -e "  ${YELLOW}⚠ ulimit -n is low ($CURRENT_ULIMIT). Recommended: 65535+${NC}"
    echo ""
    echo "  To fix, add to /etc/security/limits.conf:"
    echo "    * soft nofile 65535"
    echo "    * hard nofile 65535"
    echo ""
    echo "  Or run before starting exsocks:"
    echo "    ulimit -n 65535"
else
    echo -e "  ${GREEN}✓${NC} ulimit -n is sufficient ($CURRENT_ULIMIT)"
fi

echo ""

# ============================================================
# 持久化（可选）
# ============================================================
if [[ "$PERSIST" == true ]]; then
    echo -e "${GREEN}[INFO] Persisting to $SYSCTL_CONF ...${NC}"

    cat > "$SYSCTL_CONF" <<'SYSCTL_EOF'
# exsocks high-concurrency kernel tuning
# Generated by scripts/tune-kernel.sh
# Apply with: sysctl -p /etc/sysctl.d/99-exsocks.conf

# TCP accept queue
net.core.somaxconn = 65535

# SYN backlog
net.ipv4.tcp_max_syn_backlog = 65535

# Ephemeral port range
net.ipv4.ip_local_port_range = 1024 65535

# TIME_WAIT reuse
net.ipv4.tcp_tw_reuse = 1

# System-wide file descriptor limit
fs.file-max = 1048576

# Network device backlog
net.core.netdev_max_backlog = 65535

# TCP buffer auto-tuning (min, default, max) in bytes
net.ipv4.tcp_rmem = 4096 131072 16777216
net.ipv4.tcp_wmem = 4096 131072 16777216

# TCP memory limits (pages)
net.ipv4.tcp_mem = 98304 131072 196608

# TCP window scaling
net.ipv4.tcp_window_scaling = 1

# Reduce FIN_WAIT2 timeout
net.ipv4.tcp_fin_timeout = 15

# Faster dead connection detection
net.ipv4.tcp_keepalive_time = 300
net.ipv4.tcp_keepalive_intvl = 15
net.ipv4.tcp_keepalive_probes = 5
SYSCTL_EOF

    echo -e "  ${GREEN}✓${NC} Written to $SYSCTL_CONF"
    echo "  Parameters will survive reboot."
    echo ""
    echo "  To also persist ulimit, add to /etc/security/limits.conf:"
    echo "    * soft nofile 65535"
    echo "    * hard nofile 65535"
else
    echo -e "${YELLOW}[INFO] Parameters applied to running kernel only (will reset on reboot).${NC}"
    echo "  To persist, re-run with: sudo bash scripts/tune-kernel.sh --persist"
fi

echo ""

# ============================================================
# 验证
# ============================================================
echo -e "${CYAN}[INFO] Verification - values after tuning:${NC}"
echo ""
printf "%-42s %-25s %s\n" "PARAMETER" "EXPECTED" "ACTUAL"
printf "%-42s %-25s %s\n" "-----------------------------------------" "------------------------" "--------------------"

MISMATCH=0
for key in $(echo "${!PARAMS[@]}" | tr ' ' '\n' | sort); do
    expected="${PARAMS[$key]}"
    actual=$(sysctl -n "$key" 2>/dev/null | tr '\t' ' ' || echo "N/A")
    if [[ "$actual" == "$expected" ]]; then
        printf "%-42s %-25s ${GREEN}%s ✓${NC}\n" "$key" "$expected" "$actual"
    else
        printf "%-42s %-25s ${RED}%s ✗${NC}\n" "$key" "$expected" "$actual"
        MISMATCH=$((MISMATCH + 1))
    fi
done

echo ""

if [[ $FAILED -eq 0 ]] && [[ $MISMATCH -eq 0 ]]; then
    echo -e "${GREEN}[SUCCESS] All parameters applied successfully!${NC}"
else
    echo -e "${YELLOW}[WARNING] $FAILED failed to apply, $MISMATCH mismatched.${NC}"
    echo "  Some parameters may require a newer kernel or specific modules."
fi
